language: php

php: 
  - 7.1.0
sudo: required
before_script:
 - php artisan key:
 - cp .env.travis .env
 - composer self-update
 - composer install --no-interaction
 script:
 - pwd 
 - ./vendor/phpunit/phpunit/phpunit